train_config:
    model_name: "bert-base-cased"
    batch_size: 32
    structured_diff_pruning: True
    alpha_init: 5
    concrete_lower: -1.5
    concrete_upper: 1.5
    gradient_accumulation_steps: 1
    num_epochs_finetune: 3
    num_epochs_fixmask: 5
    weight_decay: 0.0
    learning_rate: 5e-5
    learning_rate_alpha: 0.1
    adam_epsilon: 1e-8
    warmup_steps: 0
    sparsity_pen: 1.25e-7
    max_grad_norm: 1.0
    fixmask_pct: 0.1
    output_dir: "checkpoints"
    logging_step: 5
train_config_baseline:
    model_name: "bert-base-cased"
    batch_size: 32
    num_epochs: 5
    weight_decay: 0.0
    learning_rate: 5e-5
    adam_epsilon: 1e-8
    warmup_steps: 0
    max_grad_norm: 1.0
    output_dir: "checkpoints_baseline"
    logging_step: 5
